{{/* --- [ 基础资源：Secret 与 ServiceAccount ] --- */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatwoot.full" . }}-env
  labels: {{ include "chatwoot.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_HOST: {{ include "chatwoot.db.host" . | b64enc | quote }}
  POSTGRES_PORT: {{ default "5432" .Values.postgresql.postgresqlPort | toString | b64enc | quote }}
  POSTGRES_USERNAME: {{ default "postgres" .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_DATABASE: {{ default "chatwoot_production" .Values.postgresql.auth.database | b64enc | quote }}
  {{- if and (not .Values.postgresql.enabled) (not .Values.postgresql.auth.existingSecret) }}
  {{- /* 外部 PG：密码通过 values.override.yaml 的 env.POSTGRES_PASSWORD 传入 */}}
  {{- else if not .Values.postgresql.auth.existingSecret }}
  POSTGRES_PASSWORD: {{ default "postgres" .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  {{- end }}
  REDIS_HOST: {{ include "chatwoot.cache.host" . | b64enc | quote }}
  REDIS_PORT: {{ default "6379" .Values.redis.port | toString | b64enc | quote }}
  {{- if not .Values.redis.auth.existingSecret }}
  REDIS_URL: {{ (printf "redis://%s:%s" (include "chatwoot.cache.host" .) (default "6379" .Values.redis.port | toString)) | b64enc | quote }}
  {{- else }}
  REDIS_URL: {{ (printf "redis://%s:%s" (include "chatwoot.cache.host" .) (default "6379" .Values.redis.port | toString)) | b64enc | quote }}
  {{- end }}
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
  {{- end }}
---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chatwoot.full" . }}
  labels: {{ include "chatwoot.labels" . | nindent 4 }}
{{- end }}
