apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatwoot.full" . }}-worker
  labels:
    {{- include "chatwoot.labels" . | nindent 4 }}
    role: worker
spec:
  replicas: {{ include "chatwoot.worker.replicas" . }}
  selector:
    matchLabels:
      {{- include "chatwoot.selector" . | nindent 6 }}
      role: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "chatwoot.selector" . | nindent 8 }}
        role: worker
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.env.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "chatwoot.pod.common" . | nindent 6 }}
      containers:
        - args:
            - bundle
            - exec
            - sidekiq
            - -C
            - config/sidekiq.yml
          env:
          {{- include "chatwoot.env.common" . | nindent 10 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: worker
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: cache
              mountPath: /app/tmp
      serviceAccountName: {{ include "chatwoot.serviceAccountName" . }}
      {{- if .Values.securityContext }}
      securityContext: {{ .Values.securityContext | toYaml | nindent 8 }}
      {{- end }}
