{{/* --- [ 流量入口: Ingress 控制器 ] --- */}}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ default (include "chatwoot.full" .) .Values.ingress.nameOverride }}
  labels: {{ include "chatwoot.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ default "traefik" .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls: {{ toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend: {service: {name: {{ include "chatwoot.full" $ }}, port: {number: {{ $.Values.service.port }} }}}
          {{- end }}
    {{- end }}
{{- end }}
