apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "chatwoot.full" . }}-migrate"
  labels:
    {{- include "chatwoot.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": {{ .Values.hooks.migrate.hookAnnotation | quote }}
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "-1"
spec:
  template:
    spec:
      {{- include "chatwoot.pod.common" . | nindent 6 }}
      restartPolicy: Never
      initContainers:
      - name: init-db
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh"]
        args:
          - -c
          - >-
            DB_READY="pg_isready -h {{ include "chatwoot.db.host" . }} -p {{ include "chatwoot.db.port" . }}";
            until $DB_READY;
            do
              sleep 2;
            done;
            echo "Database ready to accept connections."  ;
      - name: init-cache
        image: busybox:1.28
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c", "until nslookup {{ include "chatwoot.cache.host" . }} ; do echo waiting for {{ include "chatwoot.cache.host" . }} ; sleep 2; done;"]
      containers:
      - name: migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - bundle
        - exec
        - rails
        - db:chatwoot_prepare
        env:
        {{- include "chatwoot.env.common" . | nindent 8 }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
            - name: cache
              mountPath: /app/tmp
      serviceAccountName: {{ include "chatwoot.serviceAccountName" . }}
      {{- if .Values.securityContext }}
      securityContext: {{ .Values.securityContext | toYaml | nindent 8 }}
      {{- end }}
