apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatwoot.full" . }}
  labels:
    {{- include "chatwoot.labels" . | nindent 4 }}
  {{- with .Values.services.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.type }}
  ports:
    - name: {{ default "http" .Values.services.name | quote}}
      port: {{ int .Values.service.port }}
      targetPort: {{ int .Values.services.targetPort }}
      protocol: TCP
  selector:
    {{- include "chatwoot.selector" . | nindent 4 }}
    role: web
