{{/* --- [ Web 核心单元: Deployment + Service ] --- */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatwoot.full" . }}-web
  labels:
    {{- include "chatwoot.labels" . | nindent 4 }}
    role: web
spec:
  replicas: {{ include "chatwoot.app.replicas" (dict "context" . "component" "web") }}
  selector:
    matchLabels:
      {{- include "chatwoot.selector" . | nindent 6 }}
      role: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "chatwoot.selector" . | nindent 8 }}
        role: web
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/base.yaml") . | sha256sum }}
    spec:
      {{- include "chatwoot.pod.common" . | nindent 6 }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [docker/entrypoints/rails.sh]
          args: [bundle, exec, rails, s, -p, "{{ .Values.services.internalPort }}", -b, 0.0.0.0]
          ports:
            - containerPort: {{ .Values.services.internalPort }}
          env:
            {{- include "chatwoot.env.common" . | nindent 12 }}
          envFrom:
            {{- include "chatwoot.envFrom.common" . | nindent 12 }}
          volumeMounts:
            - name: cache
              mountPath: /app/tmp
            {{- if .Values.persistence.enabled }}
            - name: storage
              mountPath: /app/storage
            {{- end }}
          {{- if .Values.web.resources }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.internalPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api
              port: {{ .Values.services.internalPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.internalPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
---
{{/* --- [ Web 内网访问服务 ] --- */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatwoot.full" . }}
  labels:
    {{- include "chatwoot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.services.targetPort }}
      protocol: TCP
  selector:
    {{- include "chatwoot.selector" . | nindent 4 }}
    role: web
