apiVersion: v2
name: chatwoot
version: 2.1.16
appVersion: "v4.11.1"
description: "Professional Hardened Chatwoot Chart: Minimalist, Secure, and HA-ready (Artistic Edition) 🔥💬"
type: application
keywords: [chatwoot, open-source, customer-support, crm, high-availability, hardened]

home: https://github.com/webees/chatwoot
icon: https://chatwoot-public-assets.s3.amazonaws.com/logo/square.png
sources:
  - https://github.com/chatwoot/chatwoot
  - https://github.com/chatwoot/charts

dependencies:
  - name: postgresql
    version: 11.6.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 16.12.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: common
    version: 2.31.4
    repository: oci://registry-1.docker.io/bitnamicharts

maintainers:
  - name: webees
    email: hello@webees.io
